<div data-pa-eq-height="{&quot;targetType&quot;:&quot;widget&quot;,&quot;target&quot;:&quot;&quot;,&quot;enableOn&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;]}" class="elementor-element elementor-element-14a4083b e-con-full premium-equal-height-yes e-flex e-con e-parent" data-id="14a4083b" data-element_type="container" data-settings="{&quot;content_width&quot;:&quot;full&quot;,&quot;background_background&quot;:&quot;classic&quot;,&quot;premium_eq_height_switcher&quot;:&quot;yes&quot;,&quot;_ha_eqh_enable&quot;:false}" data-core-v316-plus="true">
    <div class="elementor-element elementor-element-61060923 e-flex e-con-boxed e-con e-child" data-id="61060923" data-element_type="container" data-settings="{&quot;content_width&quot;:&quot;boxed&quot;,&quot;_ha_eqh_enable&quot;:false}">
        <div class="e-con-inner">
            <div class="elementor-element elementor-element-c00038f elementor-widget-mobile__width-inherit elementor-widget__width-inherit wdp-sticky-section-no elementor-invisible elementor-widget elementor-widget-heading" data-id="c00038f" data-element_type="widget" data-settings="{&quot;_animation&quot;:&quot;fadeInUp&quot;,&quot;_animation_delay&quot;:0}" data-widget_type="heading.default">
                <div class="elementor-widget-container">
                    <h2 class="elementor-heading-title elementor-size-default">Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir<br><br>(QS. Ar Rum : 21)</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="elementor-element elementor-element-3999db7 elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-absolute premium-floating-effects-yes animated-slow wdp-sticky-section-no elementor-invisible elementor-widget elementor-widget-image" data-id="3999db7" data-element_type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;premium_fe_translate_switcher&quot;:&quot;yes&quot;,&quot;premium_fe_Xtranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-21,&quot;to&quot;:33}},&quot;premium_fe_Ytranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-9,&quot;to&quot;:8}},&quot;premium_fe_trans_duration&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:2500,&quot;sizes&quot;:[]},&quot;_animation&quot;:&quot;fadeInLeft&quot;,&quot;_animation_mobile&quot;:&quot;fadeInLeft&quot;,&quot;_animation_delay&quot;:500,&quot;premium_fe_Xtranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Xtranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_trans_delay&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_direction&quot;:&quot;alternate&quot;,&quot;premium_fe_loop&quot;:&quot;default&quot;,&quot;premium_fe_easing&quot;:&quot;easeInOutSine&quot;}" data-widget_type="image.default">
        <div class="elementor-widget-container">
            <img loading="lazy" decoding="async" width="800" height="822" src="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-6-996x1024.webp" class="attachment-large size-large wp-image-9283" alt="" srcset="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-6-996x1024.webp 996w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-6-292x300.webp 292w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-6-768x790.webp 768w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-6.webp 1028w" sizes="(max-width: 800px) 100vw, 800px" />
        </div>
    </div>
    <div class="elementor-element elementor-element-0f57819 elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-absolute animated-slow wdp-sticky-section-no elementor-invisible elementor-widget elementor-widget-image" data-id="0f57819" data-element_type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;_animation&quot;:&quot;fadeInRight&quot;,&quot;_animation_mobile&quot;:&quot;fadeInRight&quot;}" data-widget_type="image.default">
        <div class="elementor-widget-container">
            <img decoding="async" width="629" height="629" src="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-5.webp" class="attachment-large size-large wp-image-9249" alt="" srcset="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-5.webp 629w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-5-300x300.webp 300w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-5-150x150.webp 150w" sizes="(max-width: 629px) 100vw, 629px" />
        </div>
    </div>
    <div class="elementor-element elementor-element-7691a0b elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-absolute premium-floating-effects-yes animated-slow wdp-sticky-section-no elementor-invisible elementor-widget elementor-widget-image" data-id="7691a0b" data-element_type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;premium_fe_translate_switcher&quot;:&quot;yes&quot;,&quot;premium_fe_Xtranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-21,&quot;to&quot;:33}},&quot;premium_fe_Ytranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-9,&quot;to&quot;:8}},&quot;premium_fe_trans_duration&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:1500,&quot;sizes&quot;:[]},&quot;_animation&quot;:&quot;fadeInRight&quot;,&quot;_animation_mobile&quot;:&quot;fadeInRight&quot;,&quot;_animation_delay&quot;:500,&quot;premium_fe_Xtranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Xtranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_trans_delay&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_direction&quot;:&quot;alternate&quot;,&quot;premium_fe_loop&quot;:&quot;default&quot;,&quot;premium_fe_easing&quot;:&quot;easeInOutSine&quot;}" data-widget_type="image.default">
        <div class="elementor-widget-container">
            <img loading="lazy" decoding="async" width="670" height="358" src="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-4b.webp" class="attachment-large size-large wp-image-9280" alt="" srcset="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-4b.webp 670w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-4b-300x160.webp 300w" sizes="(max-width: 670px) 100vw, 670px" />
        </div>
    </div>
</div>