<div data-pa-eq-height="{&quot;targetType&quot;:&quot;widget&quot;,&quot;target&quot;:&quot;&quot;,&quot;enableOn&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;]}" class="elementor-element elementor-element-17be3709 e-con-full premium-equal-height-yes e-flex e-con e-parent" data-id="17be3709" data-element_type="container" id="cover" data-settings="{&quot;content_width&quot;:&quot;full&quot;,&quot;background_background&quot;:&quot;classic&quot;,&quot;premium_eq_height_switcher&quot;:&quot;yes&quot;,&quot;_ha_eqh_enable&quot;:false}" data-core-v316-plus="true">
    <div class="elementor-element elementor-element-0ad711c elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-absolute premium-floating-effects-yes animated-slow wdp-sticky-section-no elementor-invisible elementor-widget elementor-widget-image" data-id="0ad711c" data-element_type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;premium_fe_translate_switcher&quot;:&quot;yes&quot;,&quot;premium_fe_Xtranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-21,&quot;to&quot;:33}},&quot;premium_fe_Ytranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-9,&quot;to&quot;:8}},&quot;premium_fe_trans_duration&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:2000,&quot;sizes&quot;:[]},&quot;_animation&quot;:&quot;fadeInLeft&quot;,&quot;_animation_mobile&quot;:&quot;fadeInRight&quot;,&quot;_animation_delay&quot;:500,&quot;premium_fe_Xtranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Xtranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_trans_delay&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_direction&quot;:&quot;alternate&quot;,&quot;premium_fe_loop&quot;:&quot;default&quot;,&quot;premium_fe_easing&quot;:&quot;easeInOutSine&quot;}" data-widget_type="image.default">
        <div class="elementor-widget-container">
            <img loading="lazy" decoding="async" width="670" height="358" src="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-4b.webp" class="attachment-large size-large wp-image-9280" alt="" srcset="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-4b.webp 670w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-4b-300x160.webp 300w" sizes="(max-width: 670px) 100vw, 670px" />
        </div>
    </div>
    <div class="elementor-element elementor-element-d828a7f elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-absolute premium-floating-effects-yes animated-slow wdp-sticky-section-no elementor-invisible elementor-widget elementor-widget-image" data-id="d828a7f" data-element_type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;premium_fe_translate_switcher&quot;:&quot;yes&quot;,&quot;premium_fe_Xtranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-13,&quot;to&quot;:17}},&quot;premium_fe_Ytranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-13,&quot;to&quot;:14}},&quot;premium_fe_trans_duration&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:1500,&quot;sizes&quot;:[]},&quot;_animation&quot;:&quot;fadeInLeft&quot;,&quot;_animation_mobile&quot;:&quot;fadeInRight&quot;,&quot;_animation_delay&quot;:600,&quot;premium_fe_Xtranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Xtranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_trans_delay&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_direction&quot;:&quot;alternate&quot;,&quot;premium_fe_loop&quot;:&quot;default&quot;,&quot;premium_fe_easing&quot;:&quot;easeInOutSine&quot;}" data-widget_type="image.default">
        <div class="elementor-widget-container">
            <img loading="lazy" decoding="async" width="532" height="313" src="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-2b.webp" class="attachment-large size-large wp-image-9282" alt="" srcset="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-2b.webp 532w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-2b-300x177.webp 300w" sizes="(max-width: 532px) 100vw, 532px" />
        </div>
    </div>
    <div class="elementor-element elementor-element-389f2ee elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-absolute premium-floating-effects-yes animated-slow wdp-sticky-section-no elementor-invisible elementor-widget elementor-widget-image" data-id="389f2ee" data-element_type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;premium_fe_translate_switcher&quot;:&quot;yes&quot;,&quot;premium_fe_Xtranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-11,&quot;to&quot;:24}},&quot;premium_fe_Ytranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-14,&quot;to&quot;:20}},&quot;premium_fe_trans_duration&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:1700,&quot;sizes&quot;:[]},&quot;_animation&quot;:&quot;fadeInLeft&quot;,&quot;_animation_mobile&quot;:&quot;fadeInRight&quot;,&quot;_animation_delay&quot;:700,&quot;premium_fe_Xtranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Xtranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_trans_delay&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_direction&quot;:&quot;alternate&quot;,&quot;premium_fe_loop&quot;:&quot;default&quot;,&quot;premium_fe_easing&quot;:&quot;easeInOutSine&quot;}" data-widget_type="image.default">
        <div class="elementor-widget-container">
            <img loading="lazy" decoding="async" width="585" height="272" src="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-3b.webp" class="attachment-large size-large wp-image-9279" alt="" srcset="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-3b.webp 585w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-3b-300x139.webp 300w" sizes="(max-width: 585px) 100vw, 585px" />
        </div>
    </div>
    <div class="elementor-element elementor-element-66b1409 elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-absolute wdp-sticky-section-no elementor-widget elementor-widget-image" data-id="66b1409" data-element_type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;motion_fx_motion_fx_scrolling&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_effect&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_affectedRange&quot;:{&quot;unit&quot;:&quot;%&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;start&quot;:50,&quot;end&quot;:100}},&quot;_animation&quot;:&quot;none&quot;,&quot;_animation_mobile&quot;:&quot;none&quot;,&quot;motion_fx_translateY_speed&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:4,&quot;sizes&quot;:[]},&quot;motion_fx_devices&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;]}" data-widget_type="image.default">
        <div class="elementor-widget-container">
            <img loading="lazy" decoding="async" width="345" height="507" src="{{ asset('frontend/asset/img/fix/intro/1.JPG') }}" class="attachment-large size-large wp-image-9273" alt="" srcset="{{ asset('frontend/asset/img/fix/intro/1.JPG') }} 345w, {{ asset('frontend/asset/img/fix/intro/1.JPG') }} 204w" sizes="(max-width: 345px) 100vw, 345px" />
        </div>
    </div>
    <div class="elementor-element elementor-element-77760f9d e-flex e-con-boxed e-con e-child" data-id="77760f9d" data-element_type="container" data-settings="{&quot;content_width&quot;:&quot;boxed&quot;,&quot;_ha_eqh_enable&quot;:false}">
        <div class="e-con-inner">
            <div class="elementor-element elementor-element-36a9394 e-flex e-con-boxed e-con e-child" data-id="36a9394" data-element_type="container" data-settings="{&quot;background_background&quot;:&quot;classic&quot;,&quot;background_motion_fx_motion_fx_scrolling&quot;:&quot;yes&quot;,&quot;motion_fx_motion_fx_scrolling&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_effect&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_affectedRange&quot;:{&quot;unit&quot;:&quot;%&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;start&quot;:51,&quot;end&quot;:100}},&quot;content_width&quot;:&quot;boxed&quot;,&quot;background_motion_fx_devices&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;],&quot;_ha_eqh_enable&quot;:false,&quot;motion_fx_translateY_speed&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:4,&quot;sizes&quot;:[]},&quot;motion_fx_devices&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;]}">
                <div class="e-con-inner">
                    <div class="elementor-element elementor-element-07cbd3a e-con-full e-flex e-con e-child" data-id="07cbd3a" data-element_type="container" data-settings="{&quot;content_width&quot;:&quot;full&quot;,&quot;_ha_eqh_enable&quot;:false}">
                        <div class="elementor-element elementor-element-354550c elementor-widget__width-inherit elementor-widget-mobile__width-inherit wdp-sticky-section-no elementor-widget elementor-widget-heading" data-id="354550c" data-element_type="widget" data-widget_type="heading.default">
                            <div class="elementor-widget-container">
                                <h2 class="elementor-heading-title elementor-size-default">W<br>E<br>D<br>D<br>I<br>N<br>G<br><br>O<br>F</h2>
                            </div>
                        </div>
                    </div>
                    <div class="elementor-element elementor-element-6bd005f e-con-full e-flex e-con e-child" data-id="6bd005f" data-element_type="container" data-settings="{&quot;content_width&quot;:&quot;full&quot;,&quot;_ha_eqh_enable&quot;:false}">
                        <div class="elementor-element elementor-element-433312a6 elementor-widget__width-inherit elementor-widget-mobile__width-inherit wdp-sticky-section-no elementor-widget elementor-widget-heading" data-id="433312a6" data-element_type="widget" data-widget_type="heading.default">
                            <div class="elementor-widget-container">
                                <h2 class="elementor-heading-title elementor-size-default">J</h2>
                            </div>
                        </div>
                        <div class="elementor-element elementor-element-9482e91 elementor-widget__width-inherit elementor-widget-mobile__width-inherit wdp-sticky-section-no elementor-widget elementor-widget-heading" data-id="9482e91" data-element_type="widget" data-widget_type="heading.default">
                            <div class="elementor-widget-container">
                                <h2 class="elementor-heading-title elementor-size-default">&</h2>
                            </div>
                        </div>
                        <div class="elementor-element elementor-element-8bccfe9 elementor-widget__width-inherit elementor-widget-mobile__width-inherit wdp-sticky-section-no elementor-widget elementor-widget-heading" data-id="8bccfe9" data-element_type="widget" data-widget_type="heading.default">
                            <div class="elementor-widget-container">
                                <h2 class="elementor-heading-title elementor-size-default">N</h2>
                            </div>
                        </div>
                    </div>
                    <div class="elementor-element elementor-element-8472ff2 e-con-full e-flex e-con e-child" data-id="8472ff2" data-element_type="container" data-settings="{&quot;content_width&quot;:&quot;full&quot;,&quot;_ha_eqh_enable&quot;:false}">
                        <div class="elementor-element elementor-element-9c40011 elementor-widget__width-inherit elementor-widget-mobile__width-inherit wdp-sticky-section-no elementor-widget elementor-widget-heading" data-id="9c40011" data-element_type="widget" data-widget_type="heading.default">
                            <div class="elementor-widget-container">
                                <h2 class="elementor-heading-title elementor-size-default">09<br>06<br>24</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="elementor-element elementor-element-705eb83 elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-absolute wdp-sticky-section-no elementor-widget elementor-widget-image" data-id="705eb83" data-element_type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;motion_fx_motion_fx_scrolling&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_effect&quot;:&quot;yes&quot;,&quot;motion_fx_translateY_affectedRange&quot;:{&quot;unit&quot;:&quot;%&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;start&quot;:49,&quot;end&quot;:100}},&quot;_animation&quot;:&quot;none&quot;,&quot;_animation_mobile&quot;:&quot;none&quot;,&quot;motion_fx_translateY_speed&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:4,&quot;sizes&quot;:[]},&quot;motion_fx_devices&quot;:[&quot;desktop&quot;,&quot;tablet&quot;,&quot;mobile&quot;]}" data-widget_type="image.default">
        <div class="elementor-widget-container">
            <img loading="lazy" decoding="async" width="345" height="507" src="{{ asset('frontend/asset/img/fix/intro/2.JPG') }}" class="attachment-large size-large wp-image-9274" alt="" srcset="{{ asset('frontend/asset/img/fix/intro/2.JPG') }} 345w, {{ asset('frontend/asset/img/fix/intro/2.JPG') }} 204w" sizes="(max-width: 345px) 100vw, 345px" />
        </div>
    </div>
    <div class="elementor-element elementor-element-1eb2a19 elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-absolute premium-floating-effects-yes animated-slow wdp-sticky-section-no elementor-invisible elementor-widget elementor-widget-image" data-id="1eb2a19" data-element_type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;premium_fe_translate_switcher&quot;:&quot;yes&quot;,&quot;premium_fe_Xtranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-21,&quot;to&quot;:33}},&quot;premium_fe_Ytranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-9,&quot;to&quot;:8}},&quot;premium_fe_trans_duration&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:2000,&quot;sizes&quot;:[]},&quot;_animation&quot;:&quot;fadeInLeft&quot;,&quot;_animation_delay&quot;:500,&quot;premium_fe_Xtranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Xtranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_trans_delay&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_direction&quot;:&quot;alternate&quot;,&quot;premium_fe_loop&quot;:&quot;default&quot;,&quot;premium_fe_easing&quot;:&quot;easeInOutSine&quot;}" data-widget_type="image.default">
        <div class="elementor-widget-container">
            <img decoding="async" width="765" height="419" src="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-4.webp" class="attachment-large size-large wp-image-9252" alt="" srcset="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-4.webp 765w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-4-300x164.webp 300w" sizes="(max-width: 765px) 100vw, 765px" />
        </div>
    </div>
    <div class="elementor-element elementor-element-3593089 elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-absolute premium-floating-effects-yes animated-slow wdp-sticky-section-no elementor-invisible elementor-widget elementor-widget-image" data-id="3593089" data-element_type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;premium_fe_translate_switcher&quot;:&quot;yes&quot;,&quot;premium_fe_Xtranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-13,&quot;to&quot;:17}},&quot;premium_fe_Ytranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-13,&quot;to&quot;:14}},&quot;premium_fe_trans_duration&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:1500,&quot;sizes&quot;:[]},&quot;_animation&quot;:&quot;fadeInLeft&quot;,&quot;_animation_delay&quot;:600,&quot;premium_fe_Xtranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Xtranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_trans_delay&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_direction&quot;:&quot;alternate&quot;,&quot;premium_fe_loop&quot;:&quot;default&quot;,&quot;premium_fe_easing&quot;:&quot;easeInOutSine&quot;}" data-widget_type="image.default">
        <div class="elementor-widget-container">
            <img loading="lazy" decoding="async" width="703" height="413" src="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-2.webp" class="attachment-large size-large wp-image-9250" alt="" srcset="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-2.webp 703w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-2-300x176.webp 300w" sizes="(max-width: 703px) 100vw, 703px" />
        </div>
    </div>
    <div class="elementor-element elementor-element-b617d76 elementor-widget__width-inherit elementor-widget-mobile__width-inherit elementor-absolute premium-floating-effects-yes animated-slow wdp-sticky-section-no elementor-invisible elementor-widget elementor-widget-image" data-id="b617d76" data-element_type="widget" data-settings="{&quot;_position&quot;:&quot;absolute&quot;,&quot;premium_fe_translate_switcher&quot;:&quot;yes&quot;,&quot;premium_fe_Xtranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-11,&quot;to&quot;:24}},&quot;premium_fe_Ytranslate&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:{&quot;from&quot;:-14,&quot;to&quot;:20}},&quot;premium_fe_trans_duration&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:1700,&quot;sizes&quot;:[]},&quot;_animation&quot;:&quot;fadeInLeft&quot;,&quot;_animation_delay&quot;:700,&quot;premium_fe_Xtranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Xtranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_tablet&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_Ytranslate_mobile&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_trans_delay&quot;:{&quot;unit&quot;:&quot;px&quot;,&quot;size&quot;:&quot;&quot;,&quot;sizes&quot;:[]},&quot;premium_fe_direction&quot;:&quot;alternate&quot;,&quot;premium_fe_loop&quot;:&quot;default&quot;,&quot;premium_fe_easing&quot;:&quot;easeInOutSine&quot;}" data-widget_type="image.default">
        <div class="elementor-widget-container">
            <img loading="lazy" decoding="async" width="800" height="372" src="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-3.webp" class="attachment-large size-large wp-image-9251" alt="" srcset="https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-3.webp 881w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-3-300x140.webp 300w, https://bridesspace.my.id/wp-content/uploads/2023/11/Tema-29-asset-3-768x357.webp 768w" sizes="(max-width: 800px) 100vw, 800px" />
        </div>
    </div>
</div>